services:
    pim_textmaster.api.httpclient_factory:
        class: Pim\Bundle\TextmasterBundle\Api\ClientFactory
        arguments:
            - '@oro_config.global'
            - '@monolog.logger.textmaster'

    worldia.textmaster.api.httpclient:
        class: Textmaster\HttpClient\HttpClient
        factory: ['@pim_textmaster.api.httpclient_factory', 'createHttpClient']
        arguments:
            -
                base_uri: '%textmaster.base_uri%'
                headers:
                    X-Partner-Id: 43254561-62f2-4930-858e-2e17c8a77265

    worldia.textmaster.api.client:
        class: Textmaster\Client
        arguments:
            - '@worldia.textmaster.api.httpclient'
            - '@event_dispatcher'

    worldia.textmaster.api.manager:
        class : Textmaster\Manager
        arguments:
            - '@worldia.textmaster.api.client'
