services:
    pim_textmaster.mass_edit.job.start_projects:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'textmaster_start_projects'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_textmaster.mass_edit.step.create_projects'
                - '@pim_textmaster.mass_edit.step.add_documents'
                - '@pim_textmaster.mass_edit.step.send_projects'
                - '@pim_textmaster.mass_edit.step.launch_projects'
        tags:
            -
                name: 'akeneo_batch.job'
                connector: '%pim_enrich.connector_name.mass_edit%'
                type: '%pim_enrich.job.mass_edit_type%'

    pim_textmaster.mass_edit.job.job_parameters.default_values_provider.start_projects:
        class: '%pim_enrich.connector.job.job_parameters.default_values_provider.product_mass_edit.class%'
        arguments:
            - ['textmaster_start_projects']
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_textmaster.mass_edit.job.job_parameters.constraint_collection_provider.start_projects:
        class: '%pim_enrich.connector.job.job_parameters.constraint_collection_provider.product_mass_edit.class%'
        arguments:
            - ['textmaster_start_projects']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pim_textmaster.mass_edit.step.create_projects:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - 'textmaster.step.create_projects'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_textmaster.tasklet.create_projects'

    pim_textmaster.mass_edit.step.add_documents:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'textmaster.step.add_documents'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_enrich.reader.database.product_and_product_model'
            - '@pim_textmaster.mass_edit.processor.add_documents'
            - '@pim_connector.writer.dummy_item'

    pim_textmaster.mass_edit.step.send_projects:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - 'textmaster.step.send_projects'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_textmaster.tasklet.send_projects'

    pim_textmaster.mass_edit.step.launch_projects:
        class: Pim\Bundle\TextmasterBundle\Step\FinalizeProjectsTaskletStep
        arguments:
            - 'textmaster.step.finalize_projects'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_textmaster.tasklet.finalize_projects'
