Pim\Bundle\TextmasterBundle\Entity\Project:
    type: entity
    table: textmaster_project
    repositoryClass: Pim\Bundle\TextmasterBundle\Project\ProjectRepository
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            column: code
        name:
            type: string
            column: name
        apiTemplate:
            type: string
            column: api_template
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        username:
            type: string
            column: username
            nullable: true
